// Unit tests for studio/src/thumbnailer.cpp pure helpers (MED-13).
// No external test framework: plain asserts with a pass/fail counter,
// same style as tests/config_test.cpp. Exit code 0 = all pass.
//
// Includes thumbnailer.cpp directly (occlusion_test-style single-TU
// pattern) so the anonymous-namespace helpers are reachable without
// exposing them in the header.
//
// Also exposes a QA mode: `thumbnailer_test --gen <video>` runs the real
// Thumbnailer::GetThumb() and prints GEN-OK <thumb-path> / GEN-FAIL, used
// by the MED-13 QA evidence (0.5s + 4:3 fixtures, missing-ffmpeg failure).
#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>

#include "../studio/src/thumbnailer.cpp"

namespace {

int g_checks = 0;
int g_failures = 0;

void Check(bool cond, const std::string& name) {
  ++g_checks;
  if (cond) {
    std::cout << "[PASS] " << name << "\n";
  } else {
    ++g_failures;
    std::cout << "[FAIL] " << name << "\n";
  }
}

bool Near(double a, double b, double eps = 1e-9) {
  return std::fabs(a - b) <= eps;
}

// --- SafeSeekSeconds: -ss min(1.0, duration/2), -ss 0 on probe failure ---

void TestSafeSeekSeconds() {
  Check(Near(k6wp::SafeSeekSeconds(0.0), 0.0),
        "SafeSeekSeconds(0) = 0 (probe failed -> -ss 0)");
  Check(Near(k6wp::SafeSeekSeconds(-1.0), 0.0),
        "SafeSeekSeconds(negative) = 0 (invalid duration)");
  Check(Near(k6wp::SafeSeekSeconds(0.5), 0.25),
        "SafeSeekSeconds(0.5) = 0.25 (half of sub-1s clip)");
  Check(Near(k6wp::SafeSeekSeconds(1.0), 0.5),
        "SafeSeekSeconds(1.0) = 0.5");
  Check(Near(k6wp::SafeSeekSeconds(1.5), 0.75),
        "SafeSeekSeconds(1.5) = 0.75");
  Check(Near(k6wp::SafeSeekSeconds(2.0), 1.0),
        "SafeSeekSeconds(2.0) = 1.0 (cap)");
  Check(Near(k6wp::SafeSeekSeconds(30.0), 1.0),
        "SafeSeekSeconds(30.0) = 1.0 (cap)");
}

// --- BuildThumbCommand: aspect-preserving scale+pad, safe seek -----------

void TestBuildThumbCommand() {
  const std::filesystem::path ffmpeg = L"C:\\tools\\ffmpeg.exe";
  const std::filesystem::path video = L"C:\\videos\\clip.mp4";
  const std::filesystem::path thumb = L"C:\\thumbs\\abc.jpg";

  const std::wstring cmd =
      k6wp::BuildThumbCommand(ffmpeg, video, thumb, 0.25, 320, 180, 4);

  Check(cmd.find(L"-ss 0.25") != std::wstring::npos,
        "command contains safe seek -ss 0.25");
  Check(cmd.find(L"-ss 1 ") == std::wstring::npos,
        "command no longer contains fixed -ss 1");
  Check(cmd.find(L"-vf scale=320:180:force_original_aspect_ratio=decrease,"
                 L"pad=320:180:(ow-iw)/2:(oh-ih)/2") != std::wstring::npos,
        "command contains aspect-preserving scale+pad filter");
  Check(cmd.find(L"-s 320x180") == std::wstring::npos,
        "command no longer contains fixed -s 320x180");
  Check(cmd.find(L"-frames:v 1") != std::wstring::npos,
        "command contains -frames:v 1");
  Check(cmd.find(L"-q:v 4") != std::wstring::npos,
        "command contains -q:v 4");
  Check(cmd.find(L"\"C:\\tools\\ffmpeg.exe\"") == 0,
        "command starts with quoted ffmpeg path");
  Check(cmd.find(L"\"C:\\videos\\clip.mp4\"") != std::wstring::npos,
        "command quotes the input video");
  Check(cmd.find(L"\"C:\\thumbs\\abc.jpg\"") != std::wstring::npos,
        "command quotes the output thumb");

  // Seek formatting: whole seconds have no trailing zeros; probe-failure
  // fallback renders as -ss 0.
  const std::wstring cmd1 =
      k6wp::BuildThumbCommand(ffmpeg, video, thumb, 1.0, 320, 180, 4);
  Check(cmd1.find(L"-ss 1 ") != std::wstring::npos,
        "seek 1.0 formats as -ss 1 (no trailing zeros)");
  const std::wstring cmd0 =
      k6wp::BuildThumbCommand(ffmpeg, video, thumb, 0.0, 320, 180, 4);
  Check(cmd0.find(L"-ss 0 ") != std::wstring::npos,
        "probe-failure fallback formats as -ss 0");
}

// --- Cache key versioning: command change must invalidate old thumbs -----

void TestCacheKeyVersioning() {
  // Version marker changes the key material -> thumbs generated by the old
  // -ss 1 -s 320x180 command (thumb-v1) miss and regenerate.
  const std::filesystem::path p = L"C:\\videos\\same.mp4";
  const std::string v1 = k6wp::ThumbCacheKeyMaterial(p, 1000, 42, "thumb-v1");
  const std::string v2 = k6wp::ThumbCacheKeyMaterial(p, 1000, 42, "thumb-v2");
  Check(v1 != v2,
        "cache key material differs between thumb-v1 and thumb-v2");
  Check(k6wp::Sha1Hex(v1) != k6wp::Sha1Hex(v2),
        "cache key hash differs when command version changes");

  // Real-file path: CacheKeyHex is deterministic, 40 lowercase hex chars,
  // and changes when the file changes.
  auto dir = std::filesystem::temp_directory_path() / "k6wp_thumb_test";
  std::error_code ec;
  std::filesystem::remove_all(dir, ec);
  std::filesystem::create_directories(dir, ec);
  const auto file = dir / "clip.mp4";
  {
    std::ofstream out(file, std::ios::binary | std::ios::trunc);
    out << "fake video bytes";
  }
  const std::string key1 = k6wp::Thumbnailer::CacheKeyHex(file);
  Check(key1.size() == 40, "CacheKeyHex returns 40 hex chars");
  Check(key1.find_first_not_of("0123456789abcdef") == std::string::npos,
        "CacheKeyHex is lowercase hex");
  Check(k6wp::Thumbnailer::CacheKeyHex(file) == key1,
        "CacheKeyHex is deterministic for unchanged file");

  // Change content -> size/mtime change -> key changes.
  {
    std::ofstream out(file, std::ios::binary | std::ios::trunc);
    out << "fake video bytes, now longer";
  }
  const std::string key2 = k6wp::Thumbnailer::CacheKeyHex(file);
  Check(key2 != key1, "CacheKeyHex changes when file content changes");

  std::filesystem::remove_all(dir, ec);
}

// --- LOW-4: library.json metadata cache -----------------------------------
// CacheKeyHex must source mtime/size from the library.json index instead of
// stating every video. Proven behaviorally (no stat counters needed):
//   1. slow-path key (no library.json) == fast-path key (indexed) — the
//      index reproduces the exact stat-derived key;
//   2. deleting the videos afterwards still returns the keys — zero
//      per-video stats on a snapshot hit (old code returns "" here);
//   3. rewriting library.json invalidates the snapshot — missing videos
//      return "" again, and changed size/mtime change the key.

namespace {

std::string EscapeJsonStr(const std::string& s) {
  std::string out;
  for (char c : s) {
    if (c == '\\') {
      out += "\\\\";
    } else if (c == '"') {
      out += "\\\"";
    } else {
      out += c;
    }
  }
  return out;
}

long long FileMtimeTicks(const std::filesystem::path& p) {
  std::error_code ec;
  const auto ft = std::filesystem::last_write_time(p, ec);
  if (ec) return 0;
  return static_cast<long long>(ft.time_since_epoch().count());
}

std::uint64_t FileSizeBytes(const std::filesystem::path& p) {
  std::error_code ec;
  const auto sz = std::filesystem::file_size(p, ec);
  if (ec) return 0;
  return static_cast<std::uint64_t>(sz);
}

void WriteLibraryJson(const std::filesystem::path& lib,
                      const std::vector<std::filesystem::path>& videos) {
  std::ofstream out(lib, std::ios::binary | std::ios::trunc);
  out << "{\"version\":1,\"entries\":[";
  bool first = true;
  for (const auto& v : videos) {
    if (!first) out << ",";
    first = false;
    out << "{\"dst\":\"" << EscapeJsonStr(v.u8string()) << "\",\"mtime\":"
        << FileMtimeTicks(v) << ",\"size\":" << FileSizeBytes(v) << "}";
  }
  out << "]}";
  out.flush();
}

}  // namespace

void TestLibraryMetaCache() {
  auto dir = std::filesystem::temp_directory_path() / "k6wp_thumb_meta_test";
  std::error_code ec;
  std::filesystem::remove_all(dir, ec);
  std::filesystem::create_directories(dir, ec);
  const auto lib = dir / "library.json";
  const std::vector<std::filesystem::path> videos = {
      dir / "a.mp4",
      dir / "b.mp4",
      dir / "c.mp4",
  };
  for (size_t i = 0; i < videos.size(); ++i) {
    std::ofstream out(videos[i], std::ios::binary | std::ios::trunc);
    out << "fake video bytes #" << i << " padding-padding";
  }

  // Point the resolver at a nonexistent index -> pure slow (stat) path.
  _putenv_s("K6WP_LIBRARY_JSON", (dir / "no-such-library.json").u8string().c_str());
  std::vector<std::string> slow_keys;
  for (const auto& v : videos) {
    slow_keys.push_back(k6wp::Thumbnailer::CacheKeyHex(v));
  }
  Check(slow_keys[0].size() == 40 && slow_keys[1].size() == 40 &&
            slow_keys[2].size() == 40,
        "meta-cache: slow-path keys are 40 hex chars without library.json");

  // Write a matching index -> fast path must reproduce the stat keys exactly.
  WriteLibraryJson(lib, videos);
  _putenv_s("K6WP_LIBRARY_JSON", lib.u8string().c_str());
  for (size_t i = 0; i < videos.size(); ++i) {
    Check(k6wp::Thumbnailer::CacheKeyHex(videos[i]) == slow_keys[i],
          "meta-cache: library.json key matches stat key");
  }

  for (const auto& v : videos) {
    std::filesystem::remove(v, ec);
  }
  for (size_t i = 0; i < videos.size(); ++i) {
    Check(k6wp::Thumbnailer::CacheKeyHex(videos[i]) == slow_keys[i],
          "meta-cache: key survives video deletion (no per-video stat)");
  }

  // Rewriting library.json bumps its fingerprint -> snapshot invalidated.
  WriteLibraryJson(lib, {});
  for (const auto& v : videos) {
    Check(k6wp::Thumbnailer::CacheKeyHex(v).empty(),
          "meta-cache: library.json rewrite invalidates, missing video -> empty");
  }

  _putenv_s("K6WP_LIBRARY_JSON", "");
  std::filesystem::remove_all(dir, ec);
}

}  // namespace

int main(int argc, char** argv) {
  if (argc >= 2 && std::string(argv[1]) == "--gen") {
    // QA mode: exercise the real GetThumb() (probe + safe seek + scale/pad
    // + cache). Prints GEN-OK <thumb-path> on success, GEN-FAIL otherwise.
    // Honors K6WP_THUMBS_DIR for a scratch cache root.
    k6wp::Thumbnailer t;
    const auto thumb = t.GetThumb(argv[2]);
    if (thumb.empty()) {
      std::cout << "GEN-FAIL\n";
      return 1;
    }
    std::cout << "GEN-OK " << thumb.u8string() << "\n";
    return 0;
  }

  TestSafeSeekSeconds();
  TestBuildThumbCommand();
  TestCacheKeyVersioning();
  TestLibraryMetaCache();

  std::cout << "\n" << g_checks << " checks, " << g_failures << " failures\n";
  return g_failures == 0 ? 0 : 1;
}