#include "thumbnailer.hpp"

#include "ffmpeg_path.hpp"
#include "ffprobe_helper.hpp"
#include "sha1.hpp"
#include "thirdparty/json.hpp"

#include <cstdio>
#include <cstdint>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <mutex>
#include <sstream>
#include <system_error>
#include <unordered_map>
#include <utility>
#include <vector>

// windows.h must stay out of the header; only this .cpp needs it.
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>

// Task 23: production logging. Diagnostics mirror to stderr only in verbose
// builds (root CMake option K6WP_VERBOSE); default build stays console-clean.
#ifndef K6WP_VERBOSE
#define K6WP_VERBOSE 0
#endif

namespace k6wp {

namespace {

// MSVC-safe getenv wrapper (windows.h-free; _dupenv_s lives in <cstdlib>).
std::string GetEnvStr(const char* name) {
  char* buf = nullptr;
  std::size_t len = 0;
  if (_dupenv_s(&buf, &len, name) != 0 || buf == nullptr) {
    return "";
  }
  std::string value(buf);
  std::free(buf);
  return value;
}

constexpr wchar_t kThumbsSubdir[] = L"K6WP\\thumbs";
constexpr int kThumbWidth = 320;
constexpr int kThumbHeight = 180;
constexpr int kJpegQuality = 4;  // -q:v 4: small file, grid-grade quality
constexpr DWORD kFfmpegTimeoutMs = 10000;

// MED-13: version the thumbnail cache key so a command change (safe seek +
// aspect-preserving scale+pad) invalidates thumbs generated by the old
// -ss 1 -s 320x180 command instead of serving them forever. MED-3 (Todo 25)
// bumped to thumb-v3 when the hash moved to the shared SHA1 (k6wp_shared).
constexpr const char* kThumbCacheVersion = "thumb-v3";

void LogThumbError(const std::string& msg) {
#if K6WP_VERBOSE
  std::fputs(("[thumbnailer] " + msg + "\n").c_str(), stderr);
  std::fflush(stderr);
#else
  (void)msg;  // production: console-clean; failures surface via return value
#endif
}

// MED-13: safe input seek. -ss 1 fails on videos shorter than 1s (seek
// past EOF yields no frame). Clamp to half the duration for short clips;
// a failed/absent probe (duration <= 0) falls back to -ss 0, which always
// has a frame.
double SafeSeekSeconds(double duration_seconds) {
  if (!(duration_seconds > 0.0)) return 0.0;
  if (duration_seconds >= 2.0) return 1.0;
  return duration_seconds / 2.0;
}

// Formats a seek offset for the command line: "1" not "1.000000",
// "0.25" not "0.250000" (ffmpeg accepts both; keep the line readable).
std::wstring FormatSeekSeconds(double seconds) {
  std::wostringstream oss;
  oss << std::fixed << std::setprecision(6) << seconds;
  std::wstring s = oss.str();
  while (!s.empty() && s.back() == L'0') s.pop_back();
  if (!s.empty() && s.back() == L'.') s.pop_back();
  return s;
}

// MED-13: builds the full ffmpeg thumbnail command. Aspect-preserving
// scale+pad replaces the old fixed -s 320x180, which stretched non-16:9
// sources: scale=...:force_original_aspect_ratio=decrease fits inside the
// grid cell, pad centers it with letterbox bars.
std::wstring BuildThumbCommand(const std::filesystem::path& ffmpeg,
                               const std::filesystem::path& video,
                               const std::filesystem::path& thumb,
                               double seek_seconds, int width, int height,
                               int quality) {
  std::wstring cmd = L"\"" + ffmpeg.wstring() + L"\"";
  cmd += L" -y -ss " + FormatSeekSeconds(seek_seconds);
  cmd += L" -i \"" + video.wstring() + L"\"";
  cmd += L" -frames:v 1";
  cmd += L" -vf scale=" + std::to_wstring(width) + L":" +
         std::to_wstring(height) +
         L":force_original_aspect_ratio=decrease,pad=" +
         std::to_wstring(width) + L":" + std::to_wstring(height) +
         L":(ow-iw)/2:(oh-ih)/2";
  cmd += L" -q:v " + std::to_wstring(quality);
  cmd += L" \"" + thumb.wstring() + L"\"";
  return cmd;
}

// Cache-key material: abs-path | size | mtime | command-version. The
// version suffix is what makes a command change invalidate old thumbs.
std::string ThumbCacheKeyMaterial(const std::filesystem::path& abs,
                                   std::uint64_t size, long long mtime_count,
                                   const char* version) {
  std::string material;
  material.reserve(256);
  material += abs.u8string();
  material += '|';
  material += std::to_string(size);
  material += '|';
  material += std::to_string(mtime_count);
  material += '|';
  material += version;
  return material;
}

// LOW-4: library.json-backed metadata cache. The grid refresh path
// (LibraryWidget::Refresh -> Thumbnailer::CachedThumb per item, plus the
// async GetThumb worker) used to stat every video 3x per item
// (is_regular_file + file_size + last_write_time). library.json ALREADY
// stores mtime/size per entry (LibraryManager::RefreshStat at Add time),
// so the key material can come from that index instead of the disk.
//
// Design (read-only: library_manager.cpp is owned by a parallel task, so
// the json-path lookup below mirrors LibraryManager::DefaultLibraryJsonPath
// without touching it):
//   * One process-wide snapshot: absolute dst path -> (size, mtime).
//   * The snapshot is valid only while library.json's own (mtime, size)
//     fingerprint matches, so every Save (add/remove/re-stat) invalidates
//     it exactly. A corrupt/missing library.json means "unindexed" — the
//     caller falls back to the per-file stat path, never a wrong key.
//   * Zero-usable entries (mtime == 0 && size == 0, i.e. dst was missing at
//     Add time) are skipped, same fallback.
//   * Mutex-guarded: CachedThumb runs on the UI thread while GetThumb runs
//     on the async worker.
std::filesystem::path ResolveLibraryJsonPath() {
  const std::string override = GetEnvStr("K6WP_LIBRARY_JSON");
  if (!override.empty()) {
    return std::filesystem::path(override);
  }
  const std::string local = GetEnvStr("LOCALAPPDATA");
  if (!local.empty()) {
    return std::filesystem::path(local) / "K6WP" / "library.json";
  }
  const std::string profile = GetEnvStr("USERPROFILE");
  if (!profile.empty()) {
    return std::filesystem::path(profile) / "AppData" / "Local" / "K6WP" /
           "library.json";
  }
  return {};
}

struct LibraryMetaEntry {
  std::uint64_t size = 0;
  long long mtime = 0;
};

struct LibraryMetaSnapshot {
  std::mutex mutex;
  std::string lib_path;
  long long lib_mtime = 0;
  std::uint64_t lib_size = 0;
  bool have_fingerprint = false;
  std::unordered_map<std::string, LibraryMetaEntry> by_abs;
};

LibraryMetaSnapshot& MetaSnapshot() {
  static LibraryMetaSnapshot snapshot;
  return snapshot;
}

// Returns true + fills *out when abs_u8 is indexed in library.json with
// usable (non-zero) metadata. False on ANY miss (no file, corrupt JSON,
// unknown path, stale fingerprint re-parse failure) — the caller must fall
// back to stating the video. Never throws.
bool LookupLibraryMeta(const std::string& abs_u8, LibraryMetaEntry* out) {
  if (out == nullptr) return false;
  try {
    LibraryMetaSnapshot& snap = MetaSnapshot();
    std::lock_guard<std::mutex> lock(snap.mutex);
    const std::filesystem::path lib = ResolveLibraryJsonPath();
    if (lib.empty()) return false;
    std::error_code ec;
    const auto lib_time = std::filesystem::last_write_time(lib, ec);
    if (ec) return false;
    const std::uint64_t lib_size =
        static_cast<std::uint64_t>(std::filesystem::file_size(lib, ec));
    if (ec) return false;
    const long long lib_mtime =
        static_cast<long long>(lib_time.time_since_epoch().count());
    std::error_code aec;
    const std::string lib_key =
        std::filesystem::absolute(lib, aec).u8string();
    if (aec) return false;
    if (!snap.have_fingerprint || snap.lib_path != lib_key ||
        snap.lib_mtime != lib_mtime || snap.lib_size != lib_size) {
      // library.json changed (or first sight): re-parse the whole index.
      // One parse per Save, amortized over the N grid items.
      std::unordered_map<std::string, LibraryMetaEntry> fresh;
      std::ifstream in(lib, std::ios::binary);
      if (in) {
        try {
          const std::string text((std::istreambuf_iterator<char>(in)),
                                 std::istreambuf_iterator<char>());
          const nlohmann::json root = nlohmann::json::parse(text);
          if (root.is_object()) {
            const auto it = root.find("entries");
            if (it != root.end() && it->is_array()) {
              for (const auto& je : *it) {
                if (!je.is_object()) continue;
                const std::string dst = je.value("dst", "");
                if (dst.empty()) continue;
                std::error_code pec;
                const std::string key =
                    std::filesystem::absolute(std::filesystem::u8path(dst), pec)
                        .u8string();
                if (pec) continue;
                LibraryMetaEntry entry;
                entry.mtime = je.value("mtime", std::int64_t{0});
                entry.size = je.value("size", std::uint64_t{0});
                if (entry.mtime == 0 && entry.size == 0) continue;
                fresh.emplace(key, entry);
              }
            }
          }
        } catch (...) {
          // Corrupt library.json: index nothing (all lookups fall back to
          // per-file stats until the next Save rewrites it).
        }
      }
      snap.by_abs = std::move(fresh);
      snap.lib_path = lib_key;
      snap.lib_mtime = lib_mtime;
      snap.lib_size = lib_size;
      snap.have_fingerprint = true;
    }
    const auto it = snap.by_abs.find(abs_u8);
    if (it == snap.by_abs.end()) return false;
    *out = it->second;
    return true;
  } catch (...) {
    return false;
  }
}

}  // namespace

// ---------------------------------------------------------------------------
// Root resolution — mirrors CacheRoot() from cache_manager.cpp
// ---------------------------------------------------------------------------
Thumbnailer::Thumbnailer() : root_(ThumbsRoot()) {}

std::filesystem::path Thumbnailer::ThumbsRoot() const {
  const std::string override = GetEnvStr("K6WP_THUMBS_DIR");
  if (!override.empty()) {
    return std::filesystem::path(override);
  }
  const std::string local = GetEnvStr("LOCALAPPDATA");
  if (!local.empty()) {
    return std::filesystem::path(local) / "K6WP" / "thumbs";
  }
  const std::string profile = GetEnvStr("USERPROFILE");
  if (!profile.empty()) {
    return std::filesystem::path(profile) / "AppData" / "Local" / "K6WP" /
           "thumbs";
  }
  std::error_code ec;
  return std::filesystem::temp_directory_path(ec) / "K6WP" / "thumbs";
}

bool Thumbnailer::EnsureRoot() {
  try {
    std::error_code ec;
    std::filesystem::create_directories(root_, ec);
    if (ec) {
      LogThumbError("cannot create thumbs dir: " + ec.message());
      return false;
    }
    return true;
  } catch (const std::exception& e) {
    LogThumbError(std::string("cannot create thumbs dir: ") + e.what());
    return false;
  }
}

std::string Thumbnailer::CacheKeyHex(const std::filesystem::path& video) {
  try {
    std::error_code ec;
    const std::filesystem::path abs = std::filesystem::absolute(video, ec);
    if (ec) return "";
    // LOW-4 fast path: mtime/size from the library.json index (zero per-
    // video stats on a hit). The grid calls this per item per refresh, so
    // 100 items cost ~1 hot stat of library.json + map lookups instead of
    // 300 cold stats of the videos.
    LibraryMetaEntry meta;
    if (LookupLibraryMeta(abs.u8string(), &meta)) {
      return k6wp::Sha1Hex(ThumbCacheKeyMaterial(abs, meta.size, meta.mtime,
                                                 kThumbCacheVersion));
    }
    if (!std::filesystem::is_regular_file(abs, ec) || ec) return "";
    const std::uint64_t size =
        static_cast<std::uint64_t>(std::filesystem::file_size(abs, ec));
    if (ec) return "";
    const auto mtime = std::filesystem::last_write_time(abs, ec);
    if (ec) return "";
    const long long mtime_count =
        static_cast<long long>(mtime.time_since_epoch().count());
    return k6wp::Sha1Hex(ThumbCacheKeyMaterial(abs, size, mtime_count,
                                               kThumbCacheVersion));
  } catch (...) {
    return "";
  }
}

std::filesystem::path Thumbnailer::GetThumb(
    const std::filesystem::path& video) {
  try {
    const std::string key = CacheKeyHex(video);
    if (key.empty()) {
      LogThumbError("cannot stat input (missing?): " + video.u8string());
      return {};
    }
    const auto thumb = root_ / (key + ".jpg");

    // Cache hit: non-empty JPEG already on disk.
    std::error_code ec;
    if (std::filesystem::is_regular_file(thumb, ec) && !ec &&
        std::filesystem::file_size(thumb, ec) > 0 && !ec) {
      return thumb;
    }

    if (!EnsureRoot()) return {};

    std::error_code aec;
    const auto abs = std::filesystem::absolute(video, aec);
    if (aec) {
      LogThumbError("cannot resolve input: " + video.u8string());
      return {};
    }
    if (!GenerateTo(abs, thumb)) {
      LogThumbError("ffmpeg failed for: " + video.u8string());
      // Remove a partial output so the next call retries instead of
      // treating a 0-byte file as a hit (hit path requires size > 0).
      std::error_code dec;
      std::filesystem::remove(thumb, dec);
      return {};
    }
    return thumb;
  } catch (const std::exception& e) {
    LogThumbError(std::string("internal error: ") + e.what());
    return {};
  } catch (...) {
    LogThumbError("internal error (unknown)");
    return {};
  }
}

std::filesystem::path Thumbnailer::CachedThumb(
    const std::filesystem::path& video) const {
  try {
    const std::string key = CacheKeyHex(video);
    if (key.empty()) return {};
    const auto thumb = root_ / (key + ".jpg");
    std::error_code ec;
    if (std::filesystem::is_regular_file(thumb, ec) && !ec &&
        std::filesystem::file_size(thumb, ec) > 0 && !ec) {
      return thumb;
    }
    return {};
  } catch (...) {
    return {};
  }
}

std::filesystem::path Thumbnailer::FfmpegPath() {
  // Centralized in k6wp_shared (env override + flat + build + vendored).
  // Never throws; caller checks existence.
  try {
    return ::k6wp::FindFfmpeg();
  } catch (...) {
    return {};
  }
}

bool Thumbnailer::GenerateTo(const std::filesystem::path& video,
                             const std::filesystem::path& thumb) {
  try {
    std::error_code ec;
    if (!std::filesystem::is_regular_file(video, ec) || ec) return false;
    const auto ffmpeg = FfmpegPath();
    if (ffmpeg.empty() || !std::filesystem::exists(ffmpeg, ec) || ec) {
      return false;
    }

    // MED-13: safe seek. Probe duration once (ffprobe); on ANY probe
    // failure fall back to -ss 0 (frame 0 always exists) instead of the
    // old fixed -ss 1, which fails on videos shorter than 1s.
    double duration = 0.0;
    {
      FfprobeHelper probe;
      VideoMetadata meta;
      if (probe.Probe(video, meta)) duration = meta.duration;
    }
    const double seek = SafeSeekSeconds(duration);

    // MED-13: aspect-preserving scale+pad (see BuildThumbCommand) — the
    // old fixed -s 320x180 stretched non-16:9 sources.
    const std::wstring cmd = BuildThumbCommand(
        ffmpeg, video, thumb, seek, kThumbWidth, kThumbHeight, kJpegQuality);

    STARTUPINFOW si{};
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESTDHANDLES;

    // Redirect stdout+stderr to NUL to prevent pipe-buffer deadlock.
    HANDLE nul = CreateFileW(L"NUL", GENERIC_WRITE, FILE_SHARE_READ, nullptr,
                             OPEN_EXISTING, 0, nullptr);
    if (nul == INVALID_HANDLE_VALUE) return false;
    si.hStdOutput = nul;
    si.hStdError = nul;
    si.hStdInput = GetStdHandle(STD_INPUT_HANDLE);

    PROCESS_INFORMATION pi{};

    // CreateProcessW requires a mutable command-line buffer.
    std::vector<wchar_t> cmd_buf(cmd.begin(), cmd.end());
    cmd_buf.push_back(L'\0');

    const BOOL ok = CreateProcessW(
        ffmpeg.wstring().c_str(),  // lpApplicationName (null-terminated path)
        cmd_buf.data(),            // lpCommandLine (mutable)
        nullptr, nullptr,          // default security
        TRUE,                      // bInheritHandles (for NUL redirect)
        CREATE_NO_WINDOW,          // no console window
        nullptr, nullptr,          // inherit env, inherit cwd
        &si, &pi);

    CloseHandle(nul);
    if (!ok) return false;

    CloseHandle(pi.hThread);

    const DWORD wait = WaitForSingleObject(pi.hProcess, kFfmpegTimeoutMs);
    if (wait == WAIT_TIMEOUT) {
      TerminateProcess(pi.hProcess, 1);
      CloseHandle(pi.hProcess);
      return false;
    }

    DWORD exit_code = 1;
    GetExitCodeProcess(pi.hProcess, &exit_code);
    CloseHandle(pi.hProcess);

    return exit_code == 0 && std::filesystem::is_regular_file(thumb, ec) &&
           !ec && std::filesystem::file_size(thumb, ec) > 0 && !ec;
  } catch (...) {
    return false;
  }
}

}  // namespace k6wp
