; K6WP per-user installer (Task 27, k6wp-cleanup-wallpaper-ux).
;
; Per-user, no-UAC design:
;   - RequestExecutionLevel user  -> embedded manifest is asInvoker (never
;     requireAdministrator); installs without a UAC prompt.
;   - SetShellVarContext current  -> Start Menu / Desktop shortcuts resolve to
;     the CURRENT user's profile, never the all-users profile.
;   - InstallDir "$LOCALAPPDATA\K6WP" (NSIS 3.x $LOCALAPPDATA constant; never a
;     hardcoded C:\Users\... path).
;   - Registry writes are HKCU-only (Run value + uninstall key +
;     wallpaper-backup key). NO HKLM, NO Program Files, NO System32.
;   - Shortcut targets are K6WP.exe only, never engine.exe directly
;     (K6WP.exe is the Qt-free single-app launcher).
;
; File set mirrors packaging/make_zip.ps1 staging: K6WP.exe + engine.exe +
; studio.exe + compressor.exe (+ monitor_dump.exe when the build produced it)
; + vendored ffmpeg.exe/ffprobe.exe + vendored libmpv-2.dll + app-local VC
; runtime (vcruntime140.dll + vcruntime140_1.dll + msvcp140.dll, fresh-machine
; safety, no UAC) + the windeployqt output next to studio.exe (root *.dll +
; every plugin subdir containing *.dll) + config.json.example +
; packaging/uninstall.bat + LICENSE + LICENSES/ (GPL-2.0-or-later grant +
; third-party notices: libmpv/ffmpeg/Qt/nlohmann-json).
;
; Autostart checkbox writes EXACTLY "<installdir>\K6WP.exe" --engine --silent
; to HKCU\Software\Microsoft\Windows\CurrentVersion\Run value "K6WP", matching
; shared/autostart.cpp AutostartCommand()/SetAutostart(true). OFF (unchecked)
; leaves the value absent, matching SetAutostart(false). Default: CHECKED.
;
; Wallpaper backup: at install time the current OS wallpaper path is read via
; SystemParametersInfo SPI_GETDESKWALLPAPER and stored at
; HKCU\Software\K6WP\WallpaperBackup (REG_SZ "OsWallpaper"), so the
; uninstaller can restore it even when taskkill skips the engine's graceful
; restore path (engine/src/engine_app.cpp SaveOsWallpaper/RestoreOsWallpaper).
;
; Install (Section SEC_APP): stops this install dir's running processes
; FIRST (K6WP.exe --stop — the uninstaller's scoped helper) and snapshots a
; per-file pre-existence census, so re-running the installer over a live
; engine does not fail on a locked exe, and RollbackPartial deletes only the
; files THIS run created (audit fix H2: a failed upgrade leaves the
; previous installation intact).
;
; Uninstall (Section "Uninstall"): stops engine/studio/K6WP via
; "$INSTDIR\K6WP.exe" --stop (its own IPC quit first, then a per-PID kill
; restricted to images inside $INSTDIR - never a machine-wide image-name
; taskkill), deletes the Run value (idempotent), restores the
; wallpaper backup via SPI_SETDESKWALLPAPER when present, restores the
; HKLM lockscreen-policy backup via K6WP.exe --elevate-lockscreen off
; (self-elevating; the call blocks on the elevated worker with a bounded
; wait, and a declined prompt or a failed restore is reported to the user
; with the exact manual command) before the app files are deleted,
; removes the app files, asks keep/remove of
; %LOCALAPPDATA%\K6WP user data (silent uninstall keeps it), deletes
; shortcuts + HKCU uninstall key, removes the install dir.
;
; Stock plugins only: MUI2, LogicLib, nsExec, System. No third-party NSIS
; plugins, no Python at install time.
;
; Build (both styles work from the repo root; makensis resolves relative
; paths against the SCRIPT dir under either invocation, so plain relatives
; are used throughout and ${__FILEDIR__} is deliberately avoided - with a
; relative script path it expands to relative "packaging", which file
; directives then re-resolve against the script dir ("packaging\packaging").
; For the same reason do NOT add "!cd ${__FILEDIR__}": !cd resolves its
; argument against the script dir too and fails the relative invocation):
;   "C:\Program Files (x86)\NSIS\makensis.exe" packaging\installer.nsi
;   "C:\Program Files (x86)\NSIS\makensis.exe" C:\Users\axioo\Desktop\k6wp\packaging\installer.nsi
; Output: dist\K6WP-Setup.exe.

Unicode true
RequestExecutionLevel user
; Per-user shell context enforced at runtime (.onInit + un.onInit):
; Start Menu / Desktop resolve to the CURRENT user profile, never all-users.

!include "MUI2.nsh"
!include "LogicLib.nsh"
!include "Sections.nsh"
; Version constants generated by CMake from K6WP_VERSION (root CMakeLists.txt)
; into packaging/version.nsh - never hand-edit APP_VERSION here.
!include "version.nsh"

; ---------------------------------------------------------------------------
; Constants
; ---------------------------------------------------------------------------
!define APP_NAME "K6WP"
!define APP_VERSION "${K6WP_VERSION_STR}"
!define RUN_VALUE "K6WP"
!define RUN_SUBKEY "Software\Microsoft\Windows\CurrentVersion\Run"
!define UNINST_SUBKEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\K6WP"
!define BACKUP_SUBKEY "Software\K6WP\WallpaperBackup"

; ---------------------------------------------------------------------------
; H2 (audit remediation): upgrade-safe install.
;
; Two defects fixed here:
;   1. Install over a RUNNING engine failed at the first locked exe and then
;      rolled back by deleting the whole staged set — including the previous
;      installation's files, leaving the user with a broken install.
;   2. That rollback had no notion of "which files did this run create".
;
; SEC_APP now stops this install dir's processes (K6WP.exe --stop, the same
; scoped helper the uninstaller uses) BEFORE any extraction, and snapshots a
; per-file pre-existence census. RollbackPartial deletes ONLY files this run
; created (flag 0); pre-existing files are never touched, so a failed upgrade
; leaves the previous installation intact.
Var /GLOBAL PreExistK6WP
Var /GLOBAL PreExistEngine
Var /GLOBAL PreExistStudio
Var /GLOBAL PreExistCompressor
Var /GLOBAL PreExistMonitorDump
Var /GLOBAL PreExistFfmpeg
Var /GLOBAL PreExistFfprobe
Var /GLOBAL PreExistLibmpv
Var /GLOBAL PreExistVcruntime
Var /GLOBAL PreExistVcruntime1
Var /GLOBAL PreExistMsvcp
Var /GLOBAL PreExistConfigEx
Var /GLOBAL PreExistPlaylistEx
Var /GLOBAL PreExistUninstallBat
Var /GLOBAL PreExistLicense
Var /GLOBAL PreExistLicensesDir
Var /GLOBAL PreExistPlatformsDir
Var /GLOBAL PreExistImageformatsDir
Var /GLOBAL PreExistStylesDir
Var /GLOBAL PreExistIconenginesDir
Var /GLOBAL PreExistQmlDir
Var /GLOBAL PreExistNetinfoDir
Var /GLOBAL PreExistTlsDir

; Records 1 (exists) / 0 (absent) for one $INSTDIR-relative file or dir.
; NOTE: the delete/rollback side below uses explicit Delete and RMDir
; lines with literal targets (see RollbackPartial) because
; packaging/make_zip.ps1's ship-set assert greps every RMDir /r target
; under $INSTDIR in this script — a macro parameter would resolve to a
; placeholder name, not a staged directory, and fail the release gate.
!macro K6WP_PREFLAG_SET _var _rel
  ${If} ${FileExists} "$INSTDIR\${_rel}"
    StrCpy ${_var} 1
  ${Else}
    StrCpy ${_var} 0
  ${EndIf}
!macroend
; ---------------------------------------------------------------------------

; Build outputs. Release preset is the production source (matches the
; subsystem-WINDOWS, ProductName-K6WP branded triple verified in
; make_zip-style checks); file NAMES mirror make_zip.ps1 exactly.
!define SRCDIR "..\build\release"
!define VENDOR_FFMPEG "..\vendor\ffmpeg"
!define VENDOR_LIBMPV "..\vendor\libmpv\bin"
; Pinned app-local VC runtime (populated by make_zip.ps1 step 2f; makensis
; cannot discover the versioned VS Redist dir, so the installer consumes
; this cached copy and fails loudly when nobody staged it yet).
!define VENDOR_VC "..\vendor\vc_runtime"
; Repo root (license texts): LICENSE + LICENSES/ ship in both the ZIP
; (make_zip.ps1) and the installer; the ship-set sync assert in make_zip.ps1
; maps ${REPO_ROOT} back to the repo root.
!define REPO_ROOT ".."
!if /FileExists "${VENDOR_VC}\vcruntime140.dll"
!else
  !error "vendor\vc_runtime\vcruntime140.dll missing - run packaging\make_zip.ps1 once (it caches the CRT set) or copy vcruntime140.dll + vcruntime140_1.dll + msvcp140.dll there."
!endif

Name "${APP_NAME} ${APP_VERSION}"
OutFile "..\dist\K6WP-Setup.exe"
InstallDir "$LOCALAPPDATA\K6WP"
Icon "k6wp-on.ico"

!define MUI_ICON "k6wp-on.ico"
!define MUI_UNICON "k6wp-on.ico"
!define MUI_ABORTWARNING

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "${REPO_ROOT}\LICENSE"
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

VIProductVersion "${K6WP_VERSION_STR_4}"
VIAddVersionKey "ProductName" "${APP_NAME}"
VIAddVersionKey "CompanyName" "K6WP contributors"
VIAddVersionKey "FileDescription" "${APP_NAME} Setup"
VIAddVersionKey "FileVersion" "${APP_VERSION}"
VIAddVersionKey "ProductVersion" "${APP_VERSION}"
VIAddVersionKey "LegalCopyright" "${APP_NAME}"

Function .onInit
  SetShellVarContext current
FunctionEnd

Function un.onInit
  SetShellVarContext current
FunctionEnd

; ---------------------------------------------------------------------------
; Install sections
; ---------------------------------------------------------------------------
; NOTE: the autostart checkbox section is declared FIRST so its ${SEC_AUTO}
; index define exists when SEC_APP reads it (NSIS defines section indexes at
; the Section line; forward references do not expand). It holds no files; the
; actual Run-value write happens in SEC_APP so file staging stays ordered.
Section "Start with Windows (autostart)" SEC_AUTO
  ; Checkbox only: the actual Run-value write happens in SEC_APP so ordering
  ; with file staging stays deterministic. This section intentionally holds
  ; no files; its selected flag is the opt-in.
SectionEnd

Section "!${APP_NAME} Application (required)" SEC_APP
  SectionIn RO

  ; --- Writability pre-check (failure QA: message + no partial install) ---
  ; Must run BEFORE any File extraction so an unwritable target aborts clean
  ; with nothing copied (rollback = nothing to roll back).
  CreateDirectory "$INSTDIR"
  FileOpen $0 "$INSTDIR\.k6wp_write_test" w
  ; Label form (NOT numeric offsets: +1 means the NEXT instruction, so an
  ; "IfErrors 0 +1 / Abort" skips nothing and aborts on success). MessageBox
  ; is modal even in silent mode, so silent failures Abort without a dialog.
  IfErrors write_failed write_ok
  write_failed:
    IfSilent abort_nowrite 0
    MessageBox MB_ICONSTOP "${APP_NAME} cannot write to:$\r$\n$INSTDIR$\r$\n$\r$\nPick a writable folder. Nothing was installed."
  abort_nowrite:
    Abort
  write_ok:
  FileClose $0
  Delete "$INSTDIR\.k6wp_write_test"

  ; --- H2: stop the previous installation's processes BEFORE staging files.
  ; NSIS cannot overwrite a running exe image: without this the first File
  ; on a locked engine.exe failed, aborted the section, and the rollback
  ; (fixed below) destroyed the previous installation. K6WP.exe --stop is
  ; the scoped helper the uninstaller uses: IPC quit first, then a per-PID
  ; kill limited to images inside $INSTDIR (never a machine-wide taskkill).
  ; Its exit code is advisory — a survivor surfaces immediately at the File
  ; stage, which retries once via the extraction-error path below.
  ${If} ${FileExists} "$INSTDIR\K6WP.exe"
    DetailPrint "Stopping running ${APP_NAME} processes before install..."
    nsExec::ExecToLog '"$INSTDIR\K6WP.exe" --stop'
    Pop $0
    DetailPrint "Process stop helper exit code: $0"
  ${EndIf}

  ; --- H2: pre-install census consumed by RollbackPartial (create-only
  ; teardown so a failed upgrade keeps the previous install intact).
  !insertmacro K6WP_PREFLAG_SET $PreExistK6WP "K6WP.exe"
  !insertmacro K6WP_PREFLAG_SET $PreExistEngine "engine.exe"
  !insertmacro K6WP_PREFLAG_SET $PreExistStudio "studio.exe"
  !insertmacro K6WP_PREFLAG_SET $PreExistCompressor "compressor.exe"
  !insertmacro K6WP_PREFLAG_SET $PreExistMonitorDump "monitor_dump.exe"
  !insertmacro K6WP_PREFLAG_SET $PreExistFfmpeg "ffmpeg.exe"
  !insertmacro K6WP_PREFLAG_SET $PreExistFfprobe "ffprobe.exe"
  !insertmacro K6WP_PREFLAG_SET $PreExistLibmpv "libmpv-2.dll"
  !insertmacro K6WP_PREFLAG_SET $PreExistVcruntime "vcruntime140.dll"
  !insertmacro K6WP_PREFLAG_SET $PreExistVcruntime1 "vcruntime140_1.dll"
  !insertmacro K6WP_PREFLAG_SET $PreExistMsvcp "msvcp140.dll"
  !insertmacro K6WP_PREFLAG_SET $PreExistConfigEx "config.json.example"
  !insertmacro K6WP_PREFLAG_SET $PreExistPlaylistEx "playlist.json.example"
  !insertmacro K6WP_PREFLAG_SET $PreExistUninstallBat "uninstall.bat"
  !insertmacro K6WP_PREFLAG_SET $PreExistLicense "LICENSE"
  !insertmacro K6WP_PREFLAG_SET $PreExistLicensesDir "LICENSES"
  !insertmacro K6WP_PREFLAG_SET $PreExistPlatformsDir "platforms"
  !insertmacro K6WP_PREFLAG_SET $PreExistImageformatsDir "imageformats"
  !insertmacro K6WP_PREFLAG_SET $PreExistStylesDir "styles"
  !insertmacro K6WP_PREFLAG_SET $PreExistIconenginesDir "iconengines"
  !insertmacro K6WP_PREFLAG_SET $PreExistQmlDir "qml"
  !insertmacro K6WP_PREFLAG_SET $PreExistNetinfoDir "networkinformation"
  !insertmacro K6WP_PREFLAG_SET $PreExistTlsDir "tls"

  ; --- Belt-and-braces wallpaper backup (engine restores on clean exit too) --
  DetailPrint "Backing up current OS wallpaper path..."
  System::Alloc 520
  Pop $1
  System::Call 'user32::SystemParametersInfoW(i 115, i 260, p r1, i 0) i .r2'
  ${If} $2 <> 0
    System::Call '*$1(&w260 .r3)'
    ${If} $3 != ""
      WriteRegStr HKCU "${BACKUP_SUBKEY}" "OsWallpaper" "$3"
      DetailPrint "Wallpaper backup saved."
    ${EndIf}
  ${Else}
    DetailPrint "No OS wallpaper readable; skipping backup."
  ${EndIf}
  System::Free $1

  ; --- Application files (make_zip.ps1 file set) ---
  DetailPrint "Copying ${APP_NAME} files..."
  SetOutPath "$INSTDIR"
  File "${SRCDIR}\K6WP.exe"
  File "${SRCDIR}\engine.exe"
  File "${SRCDIR}\studio.exe"
  File "${SRCDIR}\compressor.exe"
!if /FileExists "${SRCDIR}\monitor_dump.exe"
  File "${SRCDIR}\monitor_dump.exe"
!endif
  ; Vendored helpers.
  File "${VENDOR_FFMPEG}\ffmpeg.exe"
  File "${VENDOR_FFMPEG}\ffprobe.exe"
  File "${VENDOR_LIBMPV}\libmpv-2.dll"
  ; App-local VC runtime (fresh machines without any redist).
  File "${VENDOR_VC}\vcruntime140.dll"
  File "${VENDOR_VC}\vcruntime140_1.dll"
  File "${VENDOR_VC}\msvcp140.dll"
  ; windeployqt output: every root DLL next to studio.exe ...
  File "${SRCDIR}\*.dll"
  ; ... plus every plugin subdir containing DLLs.
  ; qml/ is MANDATORY: Studio is a QML app, so the QtQuick/Controls/
  ; Layouts/Templates modules must ship or the window comes up empty.
  ; networkinformation/ + tls/ are back because Qt6Quick links Qt6Network
  ; (P4.2 dropped it back when Studio was Widgets-only; the QML rewrite makes
  ; it non-optional again). make_zip's ship-set assert enforces this list.
  ; qmltooling/ is deliberately NOT shipped - QML debugger/inspector plugins,
  ; excluded from staging in make_zip.ps1.
  File /r "${SRCDIR}\platforms"
  File /r "${SRCDIR}\imageformats"
  File /r "${SRCDIR}\styles"
  File /r "${SRCDIR}\iconengines"
  File /r "${SRCDIR}\qml"
  File /r "${SRCDIR}\networkinformation"
  File /r "${SRCDIR}\tls"
  ; Example config + playlist + portable-style uninstall helper.
  File "config.json.example"
  File "playlist.json.example"
  File "uninstall.bat"
  ; License texts (GPL-2.0-or-later grant + third-party notices; mirrors
  ; make_zip.ps1 staging, kept in sync by its ship-set assert).
  File "${REPO_ROOT}\LICENSE"
  File /r "${REPO_ROOT}\LICENSES"

  ; --- Extraction-error rollback: message + remove exactly what we staged --
  ; Label form (NOT numeric offsets: +1 means the NEXT instruction, so an
  ; "IfErrors 0 +1 / Abort" skips nothing and aborts on success).
  IfErrors files_failed files_ok
  files_failed:
    Call RollbackPartial
    Abort
  files_ok:

  ; --- Shortcuts (per-user shell context; target is K6WP.exe only) ---
  CreateDirectory "$SMPROGRAMS\${APP_NAME}"
  CreateShortCut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\K6WP.exe" "" "$INSTDIR\K6WP.exe" 0
  CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\K6WP.exe" "" "$INSTDIR\K6WP.exe" 0

  ; --- Autostart (SetAutostart-ON semantics, iff the checkbox is selected) --
  SectionGetFlags ${SEC_AUTO} $0
  IntOp $0 $0 & ${SF_SELECTED}
  ${If} $0 <> 0
    WriteRegStr HKCU "${RUN_SUBKEY}" "${RUN_VALUE}" '"$INSTDIR\K6WP.exe" --engine --silent'
    DetailPrint "Autostart enabled (HKCU Run)."
  ${Else}
    DetailPrint "Autostart skipped (checkbox unchecked)."
  ${EndIf}

  ; --- Uninstaller + Add/Remove Programs entry (HKCU, per-user) ---
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr HKCU "${UNINST_SUBKEY}" "DisplayName" "${APP_NAME} ${APP_VERSION}"
  WriteRegStr HKCU "${UNINST_SUBKEY}" "DisplayVersion" "${APP_VERSION}"
  WriteRegStr HKCU "${UNINST_SUBKEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "${UNINST_SUBKEY}" "UninstallString" '"$INSTDIR\Uninstall.exe"'
  WriteRegStr HKCU "${UNINST_SUBKEY}" "DisplayIcon" "$INSTDIR\K6WP.exe"
  WriteRegDWORD HKCU "${UNINST_SUBKEY}" "NoModify" 1
  WriteRegDWORD HKCU "${UNINST_SUBKEY}" "NoRepair" 1
SectionEnd

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC_APP} "Required ${APP_NAME} program files (per-user, no admin)."
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC_AUTO} "Launch ${APP_NAME} engine silently at logon via HKCU Run (no UAC). Uncheck to skip."
!insertmacro MUI_FUNCTION_DESCRIPTION_END

; Rollback helper (audit fix H2): delete exactly the files THIS run
; created — the pre-install census (K6WP_PREFLAG_SET) decides per file, so
; the previous installation's files are never touched. A failed upgrade
; therefore leaves the old version installed (and uninstallable) instead of
; a blown-away install dir.
; Deliberate omissions vs the file list:
;   - root "*.dll" wildcard: version-specific Qt payloads we cannot census
;     individually; leftover DLLs are inert next to the old exes.
;   - Uninstall.exe / the HKCU entries are never written before extraction
;     completes, so they cannot need rollback.
Function RollbackPartial
  ; Silent-safe: MessageBox would block a headless /S run, so only show it
  ; interactively; silent runs still delete the partial set and Abort.
  IfSilent rb_skip_msg 0
  MessageBox MB_ICONSTOP "${APP_NAME} setup failed while copying files. Rolling back the partial install."
rb_skip_msg:
  ; Explicit Delete and RMDir lines with literal targets on purpose: the
  ; make_zip ship-set assert parses these lines, so no macro may generate
  ; them (see the NOTE next to K6WP_PREFLAG_SET above).
  ${If} $PreExistK6WP == 0
    Delete "$INSTDIR\K6WP.exe"
  ${EndIf}
  ${If} $PreExistEngine == 0
    Delete "$INSTDIR\engine.exe"
  ${EndIf}
  ${If} $PreExistStudio == 0
    Delete "$INSTDIR\studio.exe"
  ${EndIf}
  ${If} $PreExistCompressor == 0
    Delete "$INSTDIR\compressor.exe"
  ${EndIf}
  ${If} $PreExistMonitorDump == 0
    Delete "$INSTDIR\monitor_dump.exe"
  ${EndIf}
  ${If} $PreExistFfmpeg == 0
    Delete "$INSTDIR\ffmpeg.exe"
  ${EndIf}
  ${If} $PreExistFfprobe == 0
    Delete "$INSTDIR\ffprobe.exe"
  ${EndIf}
  ${If} $PreExistLibmpv == 0
    Delete "$INSTDIR\libmpv-2.dll"
  ${EndIf}
  ${If} $PreExistVcruntime == 0
    Delete "$INSTDIR\vcruntime140.dll"
  ${EndIf}
  ${If} $PreExistVcruntime1 == 0
    Delete "$INSTDIR\vcruntime140_1.dll"
  ${EndIf}
  ${If} $PreExistMsvcp == 0
    Delete "$INSTDIR\msvcp140.dll"
  ${EndIf}
  ${If} $PreExistConfigEx == 0
    Delete "$INSTDIR\config.json.example"
  ${EndIf}
  ${If} $PreExistPlaylistEx == 0
    Delete "$INSTDIR\playlist.json.example"
  ${EndIf}
  ${If} $PreExistUninstallBat == 0
    Delete "$INSTDIR\uninstall.bat"
  ${EndIf}
  ${If} $PreExistLicense == 0
    Delete "$INSTDIR\LICENSE"
  ${EndIf}
  ${If} $PreExistLicensesDir == 0
    RMDir /r "$INSTDIR\LICENSES"
  ${EndIf}
  ${If} $PreExistPlatformsDir == 0
    RMDir /r "$INSTDIR\platforms"
  ${EndIf}
  ${If} $PreExistImageformatsDir == 0
    RMDir /r "$INSTDIR\imageformats"
  ${EndIf}
  ${If} $PreExistStylesDir == 0
    RMDir /r "$INSTDIR\styles"
  ${EndIf}
  ${If} $PreExistIconenginesDir == 0
    RMDir /r "$INSTDIR\iconengines"
  ${EndIf}
  ${If} $PreExistQmlDir == 0
    RMDir /r "$INSTDIR\qml"
  ${EndIf}
  ${If} $PreExistNetinfoDir == 0
    RMDir /r "$INSTDIR\networkinformation"
  ${EndIf}
  ${If} $PreExistTlsDir == 0
    RMDir /r "$INSTDIR\tls"
  ${EndIf}
  Delete "$INSTDIR\.k6wp_write_test"
  RMDir "$INSTDIR"  ; only succeeds when the dir is empty
FunctionEnd

; ---------------------------------------------------------------------------
; Uninstall section (Task 28 reuses this; keep it complete and idempotent)
; ---------------------------------------------------------------------------
Section "Uninstall" SEC_UNINST
  ; --- Stop running processes first (graceful engine shutdown restores the
  ; --- OS wallpaper itself; exit codes tolerated: not-running is fine) ---
  ; K6WP.exe --stop is used instead of `taskkill /F /IM engine.exe`: an image
  ; name is not unique on a developer or IT machine, and the old call killed
  ; EVERY process on the box carrying that name. --stop asks the engine to quit
  ; over its own IPC pipe (so its wallpaper restore runs), then escalates to a
  ; per-PID kill, and only for images that live directly in $INSTDIR. A
  ; non-zero exit means one of OUR processes survived, so the user is asked to
  ; close it and retry instead of us deleting files under a live process.
  DetailPrint "Stopping ${APP_NAME} processes..."
  IntOp $1 0 + 2
  stop_processes:
    ExecWait '"$INSTDIR\K6WP.exe" --stop' $0
    ${If} $0 == 0
      Goto stop_processes_done
    ${EndIf}
    IntOp $1 1 - 1
    ${If} $1 == 0
      DetailPrint "Some ${APP_NAME} processes could not be stopped (2 attempts)."
      Goto stop_processes_done
    ${EndIf}
    IfSilent stop_processes 0
    MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION "Some ${APP_NAME} processes (engine, Studio) are still running and could not be stopped.$\r$\nClose them now, then choose Retry.$\r$\n$\r$\nChoose Cancel to continue anyway (their files may be left behind)." /SD IDCANCEL IDRETRY stop_processes
  stop_processes_done:

  ; --- Remove autostart (idempotent: absent value is not an error) ---
  DeleteRegValue HKCU "${RUN_SUBKEY}" "${RUN_VALUE}"

  ; --- Restore pre-install wallpaper backup when present ---
  ReadRegStr $0 HKCU "${BACKUP_SUBKEY}" "OsWallpaper"
  ${If} $0 != ""
    DetailPrint "Restoring backed-up OS wallpaper..."
    System::Call 'user32::SystemParametersInfoW(i 20, i 0, w r0, i 3) i .r1'
  ${EndIf}
  DeleteRegKey HKCU "${BACKUP_SUBKEY}"

  ; --- Restore lockscreen-policy backup when present (LOW-21) ---
  ; The HKLM LockScreenImage policy needs elevation, which this per-user
  ; (asInvoker) uninstaller does not have. K6WP.exe self-elevates via a
  ; runas relaunch for --elevate-lockscreen, so delegate to it while it
  ; still exists (app files are deleted below).
  ; The wait is the point: K6WP.exe hands back the elevated process HANDLE and
  ; blocks on it with a bounded wait (2 min), so this ExecWait only returns once
  ; the HKLM write is done - or once the helper was terminated. Deleting
  ; K6WP.exe while the worker is still running is impossible from here.
  ; Exit codes: 0 restored | 5 UAC declined | 4 wait budget expired |
  ; 3 the helper failed. Anything non-zero leaves the HKLM policy in place
  ; pointing at %PROGRAMDATA%\K6WP\lockscreen.jpg, which is NOT under $INSTDIR
  ; and is never removed, so the user is told exactly what to run.
  DetailPrint "Restoring lockscreen policy backup (UAC prompt expected)..."
  ExecWait '"$INSTDIR\K6WP.exe" --elevate-lockscreen off' $0
  ${If} $0 != 0
    DetailPrint "Lockscreen policy was NOT restored (exit code $0)."
    Goto lockscreen_warning
  ${EndIf}
  Goto lockscreen_done
  lockscreen_warning:
    IfSilent lockscreen_done 0
    ${If} $0 == 5
      MessageBox MB_ICONEXCLAMATION "The administrator prompt was declined, so the K6WP lockscreen policy was NOT restored.$\r$\n$\r$\nIt still points at %PROGRAMDATA%\K6WP\lockscreen.jpg (HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization\LockScreenImage). That file is not part of this uninstall, so your lockscreen stays on that image.$\r$\n$\r$\nTo restore it later, run this in an Administrator Command Prompt:$\r$\n$\r$\nK6WP.exe --elevate-lockscreen off"
    ${Else}
      MessageBox MB_ICONEXCLAMATION "K6WP could not restore the lockscreen policy (exit code $0).$\r$\n$\r$\nIt may still point at %PROGRAMDATA%\K6WP\lockscreen.jpg (HKLM\SOFTWARE\Policies\Microsoft\Windows\Personalization\LockScreenImage). That file is not part of this uninstall, so your lockscreen stays on that image.$\r$\n$\r$\nTo restore it later, run this in an Administrator Command Prompt:$\r$\n$\r$\nK6WP.exe --elevate-lockscreen off"
    ${EndIf}
  lockscreen_done:

  ; --- Remove app files (explicit staged set; user data untouched here) ---
  Delete "$INSTDIR\K6WP.exe"
  Delete "$INSTDIR\engine.exe"
  Delete "$INSTDIR\studio.exe"
  Delete "$INSTDIR\compressor.exe"
  Delete "$INSTDIR\monitor_dump.exe"
  Delete "$INSTDIR\ffmpeg.exe"
  Delete "$INSTDIR\ffprobe.exe"
  Delete "$INSTDIR\libmpv-2.dll"
  Delete "$INSTDIR\vcruntime140.dll"
  Delete "$INSTDIR\vcruntime140_1.dll"
  Delete "$INSTDIR\msvcp140.dll"
  Delete "$INSTDIR\*.dll"
  RMDir /r "$INSTDIR\platforms"
  RMDir /r "$INSTDIR\imageformats"
  RMDir /r "$INSTDIR\styles"
  RMDir /r "$INSTDIR\iconengines"
  RMDir /r "$INSTDIR\qml"
  RMDir /r "$INSTDIR\networkinformation"
  RMDir /r "$INSTDIR\tls"
  Delete "$INSTDIR\config.json.example"
  Delete "$INSTDIR\playlist.json.example"
  Delete "$INSTDIR\uninstall.bat"
  Delete "$INSTDIR\LICENSE"
  RMDir /r "$INSTDIR\LICENSES"

  ; --- User data: keep/remove offer (silent uninstall keeps it) ---
  ; Runtime data (config.json, library, thumbs, engine.log) lives under
  ; %LOCALAPPDATA%\K6WP, which equals $INSTDIR for default installs.
  StrCmp "$INSTDIR" "$LOCALAPPDATA\${APP_NAME}" same_dir custom_dir

  same_dir:
    IfSilent keep_same 0
    MessageBox MB_YESNO "Also delete ${APP_NAME} user data (settings, library, logs) in %LOCALAPPDATA%\${APP_NAME}?" IDYES remove_same IDNO keep_same
  remove_same:
    Delete "$INSTDIR\Uninstall.exe"
    RMDir /r "$INSTDIR"
    Goto done_data
  keep_same:
    DetailPrint "Keeping user data."
    Delete "$INSTDIR\Uninstall.exe"
    RMDir "$INSTDIR"
    Goto done_data

  custom_dir:
    Delete "$INSTDIR\Uninstall.exe"
    RMDir /r "$INSTDIR"
    IfSilent silent_keep 0
    MessageBox MB_YESNO "Also delete ${APP_NAME} user data (settings, library, logs) in %LOCALAPPDATA%\${APP_NAME}?" IDYES wipe_data IDNO silent_keep
  wipe_data:
    RMDir /r "$LOCALAPPDATA\${APP_NAME}"
  silent_keep:
    Goto done_data
  done_data:

  ; --- Shortcuts + Add/Remove entry ---
  Delete "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk"
  RMDir "$SMPROGRAMS\${APP_NAME}"
  Delete "$DESKTOP\${APP_NAME}.lnk"
  DeleteRegKey HKCU "${UNINST_SUBKEY}"
SectionEnd
